# Generated by Django 2.0.7 on 2018-08-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0003_auto_20180731_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='training',
        ),
    ]
