# Generated by Django 2.0.7 on 2018-08-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon', '0004_remove_employee_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon.Employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangazon.Training')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.ManyToManyField(through='bangazon.EmployeeTraining', to='bangazon.Training'),
        ),
    ]
